version: '3.7'
services:
  db:
      image: database
      restart: always
      healthcheck:
       test: ["CMD", "pg_isready -U postgres"]
       interval: 5s
       timeout: 5s
       retries: 10
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'

  chatserver:
      image:  chat
      ports:
        - "1337:1337"
        
  frontend:
      image: webclient
      ports:
        - "8080:80"

  authserver: 
      image: expressauth
      command: ["bash", "./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev" ]
      ports:
        - "3000:3000"
